### PR TITLE
Align PR template with other repos

### PR DESCRIPTION
**Pull request by rmccar**
### What is the context of this PR?
Formats the PR template to align with PR templates on other repos

### How to review 
Check changes

### CODE REVIEW

**Comment by rmccar** [comment]
[eq-infrastructure-deploy-image rename default branch](https://trello.com/c/UO7BnCm1/5590-eq-infrastructure-deploy-image-rename-default-branch)

**Review by creativeappdevamit — COMMENTED** [review]
@rmccar - no changes except the fomatting

**Comment by rmccar** [comment]
> @rmccar - no changes except the fomatting

Yeah thats all the change is. I noticed some whitespace etc when doing the branch rename so just raised a PR to fix it

**Comment by creativeappdevamit** [comment]
> @rmccar - no changes except the fomatting

👍

**Review by creativeappdevamit — APPROVED** [review]
Tested Looks good to me

**Review by Yuyuutsu — APPROVED** [review]

**Pull request merged**
